/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.creating.www;

import java.io.IOException;
import java.io.InputStream;
import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.creating.www.beans.One;
import org.creating.www.daos.OneDao;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
	static Logger logger=LoggerFactory.getLogger(App.class);
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
    	String env="development";
    	InputStream is=Resources.getResourceAsStream("Mybatis-config.xml");
    	/**
    	BufferedReader br=new BufferedReader(new InputStreamReader(is));
    	String line=null;
    	while((line=br.readLine())!=null) {
    		System.out.println(line);
    	}
    	*/
        SqlSessionFactory sessions=new  SqlSessionFactoryBuilder().build(is, env);
        try(SqlSession session=sessions.openSession()){
        	OneDao oneDao=session.getMapper(OneDao.class);
        	One one=oneDao.select("name","a");
        	logger.debug(one.toString());
        }
    }
}
