/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.creating.www;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;

import javax.sql.DataSource;

import org.apache.ibatis.datasource.pooled.PooledDataSource;
import org.apache.ibatis.io.Resources;
import org.apache.ibatis.mapping.Environment;
import org.apache.ibatis.session.Configuration;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.apache.ibatis.transaction.TransactionFactory;
import org.apache.ibatis.transaction.jdbc.JdbcTransactionFactory;
import org.creating.www.beans.One;
import org.creating.www.daos.OneDao;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class JAVAConfigApp {
	static Logger logger=LoggerFactory.getLogger(JAVAConfigApp.class);
    public static void main(String[] args) throws IOException {
    String driver="com.mysql.jdbc.Driver";
    String url="jdbc:mysql://192.168.204.130:3306/hello?useSSL=false";
    String username="root";
    String password="root";
    DataSource dataSource = new PooledDataSource(driver,url,username,password);
    TransactionFactory transactionFactory = new JdbcTransactionFactory();
    Environment environment = new Environment("development", transactionFactory, dataSource);
    Configuration configuration = new Configuration(environment);
    configuration.addMapper(OneDao.class);
    SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(configuration);
    logger.debug("started");
    try(SqlSession sqlSess=sqlSessionFactory.openSession()){
    	One o=sqlSess.getMapper(OneDao.class).select("name", "a");
    	logger.debug(o.toString());
    }
    }
}
